services:
  - type: web
    name: vowcanvas-backend
    env: docker
    rootDir: love-website
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
